-- EJEMPLO (solo si sistemas lo aprueba): guardar contraseña en texto plano en Usuarios.Clave
-- para un usuario concreto, cuando el valor legacy en NVARCHAR no coincide con ningún
-- algoritmo estándar y necesitás desbloquear Compras Verdu antes de migrar hashes.
--
-- La app en modo EXTERNAL_USUARIOS_PASSWORD_MODE=auto o plain validará contra esta columna.
--
-- UPDATE dbo.Usuarios SET Clave = N'TuContraseñaSegura' WHERE Codigo = 2546;
