-- EJEMPLO (solo si sistemas lo aprueba): guardar contraseña en texto plano en Usuarios.Clave
-- cuando el valor legacy no coincide con MD5/bcrypt/PWDCOMPARE (ver scripts/analyze-cespedes-password.js).
--
-- La API en modo `auto` prueba primero texto plano; así Compras Verdu puede validar sin el cifrado del ERP.
--
-- UPDATE dbo.Usuarios SET Clave = N'TuContraseñaSegura' WHERE Codigo = 2546;
--
-- O desde Node: node scripts/set-cespedes-clave-plano.js
